package de.cocondo.app.domain.personnel.person.mapper;

import de.cocondo.app.domain.personnel.person.Person;
import de.cocondo.app.domain.personnel.person.dto.PersonDTO;
import de.cocondo.app.domain.personnel.person.dto.PersonPayloadDTO;
import org.mapstruct.Mapper;

/**
 * file: /opt/cocondo/personnel/src/main/java/de/cocondo/app/domain/personnel/person/mapper/PersonMapper.java
 *
 * MapStruct mapper for the Person aggregate. // MapStruct-Mapper für das Aggregat Person
 *
 * This mapper transforms: // Dieser Mapper transformiert:
 * - Person entities to DTOs // Person-Entitäten zu DTOs
 * - payload DTOs to Person entities // Payload-DTOs zu Person-Entitäten
 *
 * ID handling: // ID-Behandlung:
 * - ID is generated by DomainEntityListener // ID wird durch DomainEntityListener erzeugt
 * - No ID mapping is performed here // Es erfolgt kein ID-Mapping im Mapper
 */
@Mapper(componentModel = "spring")
public interface PersonMapper {

    PersonDTO toDto(Person person); // Entity → DTO

    Person fromPayload(PersonPayloadDTO payloadDTO); // Payload → Entity
}
