package de.cocondo.app.domain.personnel.person.mapper;

import de.cocondo.app.domain.personnel.person.Person;
import de.cocondo.app.domain.personnel.person.dto.PersonDTO;
import de.cocondo.app.domain.personnel.person.dto.PersonPayloadDTO;
import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;

/**
 * MapStruct mapper for the Person aggregate.
 *
 * ID handling:
 * - ID is generated by DomainEntityListener
 * - No ID mapping is performed here
 */
@Mapper(componentModel = "spring")
public interface PersonMapper {

    PersonDTO toDto(Person person);

    Person fromPayload(PersonPayloadDTO payloadDTO);

    void updateFromPayload(PersonPayloadDTO payloadDTO, @MappingTarget Person person);
}
